services:
    contao_calendar.listener.generate_page:
        class: Contao\TifBundle\EventListener\GeneratePageListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: generatePage }
        public: true

    contao_calendar.listener.insert_tags:
        class: Contao\TifBundle\EventListener\InsertTagsListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }
        public: true

    contao_calendar.listener.preview_url_create:
        class: Contao\TifBundle\EventListener\PreviewUrlCreateListener
        arguments:
            - '@request_stack'
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao_calendar.listener.preview_url_convert:
        class: Contao\TifBundle\EventListener\PreviewUrlConvertListener
        arguments:
            - '@contao.framework'
        tags:
            - kernel.event_listener
   