services:
  Conrat\TifBundle\EventListener\PostLoginListener:
    arguments:
      - "@contao.framework"
      - "@session"
      - Contao\BackendUser
      - "@?logger"
    public: true
  Conrat\TifBundle\EventListener\PostLogoutListener:
    arguments:
      - "@contao.framework"
      - "@session"
      - Contao\BackendUser
      - "@?logger"
    public: true
  Conrat\TifBundle\EventListener\GetUserNavigationListener:
    arguments:
      - "@contao.framework"
      - "@session"
      - Contao\BackendUser
      - "@?logger"
    public: true
